apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: overcloud
  namespace: openstack
spec:
  gitSecret: git-secret
  openStackClientImageURL: quay.io/openstack-k8s-operators/rhosp17-openstack-tripleoclient:17.0_20210720.1
  openStackClientNetworks:
    - ctlplane
    - external
  openStackClientStorageClass: host-nfs-storageclass
  virtualMachineRoles:
    controller:
      roleName: Controller
      roleCount: 0
      cores: 2
      memory: 20
      diskSize: 50
      storageClass: host-nfs-storageclass
      baseImageVolumeName: openstack-base-img
      ctlplaneInterface: enp2s0 #defaults to enp2s0
      networks:
      - ctlplane
      - external
      - internalapi
      - tenant
      - storage
      - storagemgmt
