apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackClient
metadata:
  name: openstackclient
  namespace: openstack
spec:
  imageURL: quay.io/openstack-k8s-operators/rhosp17-openstack-tripleoclient:17.0_20210720.1
  deploymentSSHSecret: osp-controlplane-ssh-keys
  networks:
    - ctlplane
  storageClass: host-nfs-storageclass
